package de.caritas.cob.agencyservice.api.exception.httpresponses;

public enum HttpStatusExceptionReason {
  INVALID_POSTCODE,
  INVALID_DEMOGRAPHICS_EMPTY_GENDERS,
  INVALID_DEMOGRAPHICS_EMPTY_AGE_FROM,
  INVALID_DEMOGRAPHICS_NULL_OBJECT,
  INVALID_CONSULTING_TYPE,
  INVALID_OFFLINE_STATUS,
  AGENCY_CONTAINS_CONSULTANTS,
  AGENCY_CONTAINS_NO_CONSULTANTS,
  AGENCY_IS_ALREADY_TEAM_AGENCY,
  AGENCY_IS_ALREADY_DEFAULT_AGENCY,
  DATA_PROTECTION_OFFICER_IS_EMPTY,
  DATA_PROTECTION_RESPONSIBLE_IS_EMPTY,

  DATA_PROTECTION_ALTERNATIVE_RESPONSIBLE_IS_EMPTY,

  DATA_PROTECTION_DTO_IS_NULL,

  AGENCY_ACCESS_DENIED
}
