name: Feature Branch

on:
  push:
    branches-ignore:
      - "develop"
      - "staging"
      - "release"
jobs:
  test:
    name: Build and run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JVM
        uses: actions/setup-java@v1
        with:
          java-version: 17.0.7
          java-package: jdk
          architecture: x64

      - name: Caching maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Maven Package
        run: mvn -B -Pprod  clean package -DskipTests

      - name: Maven Verify
        run: mvn -B -Pprod clean verify
